default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oui_chef_development
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  port: 5432
  database: oui_chef_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: oui_chef_production
  username: oui_chef
  password: <%= ENV['OUI_CHEF_DATABASE_PASSWORD'] %>
